### ISSUE TITLE
 Editor van Night werkt niet

### ISSUE THREAD

**Issue by MikeChermin** [WaalbrugWire/Roster-Planner#1]
Employee: Editor van Night werkt niet.

**Comment by BR50Kab** [comment]
The form has a text box to display the contents of the boolean night property of ShiftType.

The getter in TabShiftTypePanel tries to equal to a boolean value instead of a string and therefore always returns false and the value is not stored.

wrong:
public Boolean getNight(){
        return jNightTextField.getText().equals(true);
    }

right:
public Boolean getNight(){
        return jNightTextField.getText().equals("true");
    }

I will apply the correct changes.

**Comment by MikeChermin** [comment]
Was fixed in #4

**Comment by Cranium1** [comment]
solved in v0.36
